app = 'mosquitto-render'
primary_region = 'lhr'

[build]

[[services]]
  internal_port = 1883
  protocol = "tcp"

  [[services.ports]]
    port = 1883
    handlers = []  # TCP puro — sem TLS ou HTTP

[deploy]
  strategy = "immediate"

[scale]
  count = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
